# Generated by Django 4.0.2 on 2022-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=None, default=None, null=True, upload_to='brand/'),
        ),
    ]
