# Generated by Django 4.0.2 on 2022-03-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='costumer.address'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
