# Generated by Django 4.0.2 on 2022-03-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cart_address_alter_cart_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
